# Generated by Django 3.2.7 on 2021-09-10 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitemlist',
            name='buyers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
